function test_list = get_full_test_list()
    % add new test names here! the name should correspond to a function in ./tests

    test_list = { ...
                  'test_make_vm'; ...
                  'test_generate_parameter_sweep_HL'; ...
                  'test_load_vbr_box'; ...
                };

end